name: Deployment

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  deploy-container:
    runs-on: ubuntu-latest
    steps:
      # checkout repo
      - name: checkout github actions
        uses: actions/checkout@master

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/docker-login@v1
        with:
          login-server: index.docker.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
            docker build -t mikqi/hooks-movie-app:${{ github.sha }}
            docker push mikqi/hooks-movie-app:${{ github.sha }}

        - name: Deploy to Azure Container Instances
          uses: azure/aci-deploy@v1
          with:
            resource-group: learning
            dns-name-label: hooks-movie-app
            image: mikqi/hooks-movie-app:${{ github.sha }}
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            name: hooks-movie-app
            location: Southeast Asia
